### ISSUE TITLE
map gone

### ISSUE THREAD

**Issue by mortezahosseinee** [mapbox/mapbox-android-demo#1013]
Hi, i'm using mapbox v 6.5.0 in android project. i have a problem. sometimes after switch between app pages and go back to main activity that holds mapview, everythings gone and map hides. after along time search i decided to increase mapbox version. of course i have other module in my app and increase mapbox version has side effect; so i prefer to not increase version. by the way help me what am i shoud to do.

**Comment by jealalbar** [comment]
Meg's to master

**Comment by mortezahosseinee** [comment]
same issue in v 6.8.1

**Comment by AliKhoshraftar** [comment]
Same issue for me . this is not only depends on switching between views. it will happen when i add much diffrent markers and data on map . sometimes it will be gone and sometimes is ok. so i can't check when it happens exactly . when it happened it will not load map tiles , but markers and every annotation is ok . what is wrong ?

**Comment by langsmith** [comment]
Hi all. Thanks for using Mapbox. The issues you describe are more related to the Maps SDK in https://github.com/mapbox/mapbox-gl-native, rather than an issue with this particular demo app. If you're still having problems, please open a ticket via https://github.com/mapbox/mapbox-gl-native/issues/new?template=android.md . Be sure to provide any code that you can share, so that we can get a sense of what your setup looks like. A minimally reproducible setup would be great. 

I also highly recommend that you use the latest Maps SDK version, which is `7.3.0`. It could be that your device issues have been solved between `6.5.0`/`6.8.1` and `7.3.0`. [Here's our `6.x.x` –> `7.x.x` migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide).
