### ISSUE TITLE
Location Component, LocationEngine/Request problem

### ISSUE THREAD

**Issue by marcosdecris** [mapbox/mapbox-android-demo#1052]
I`m using LocationComponent to show the User location on the map, no navigation. My component always returns the location every 20 seconds, even if i try to pass a locationRequest with diferent time interval.

Is it ok the way i`m doing it? 

Here is my code.
https://stackoverflow.com/questions/55974312/mapbox-loactioncomponent-return-location-problem

**Comment by langsmith** [comment]
Hi @marcosdecris , thanks for using Mapbox. We really appreciate it. Tickets in this repo should be about the demo app specifically, rather than general Mapbox implementation questions. Please send your technical help request to Mapbox via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 and we'll get you set up.  

In the meantime, please see https://docs.mapbox.com/help/tutorials/android-location-listening/. `DEFAULT_INTERVAL_IN_MILLISECONDS` and `DEFAULT_MAX_WAIT_TIME` are used in the tutorial to set custom times. Please try this setup.
