### ISSUE TITLE
Mapbox Markers disappearing and changing location on zoom

### ISSUE THREAD

**Issue by TankJK** [mapbox/mapbox-android-demo#1057]

**Comment by TankJK** [comment]
Hi there,

Our Android application needs to show various markers with one getting selected at a given moment. All markers have different images.

We are using Mapbox extensively in our app. Now we are going to shift to SymbolLayer for adding the marker but facing the issues.



Demo application is using:
Application is using com.mapbox.mapboxsdk:mapbox-android-sdk:7.3.2

I have tried the demo given at
https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java

There are 3 issues:
1. Whenever marker is selected, other marker is getting disappeared. The selected marker also changes its base position.
2. When zoom is done, marker are shifting their position
3. While zooming, some of the markers are getting disappeared

Please see the attached videos in zip file which shows all of the above issues.

Your help would be appreciated as we wanted to launch with updated mapbox version soon.

Thanking you,
TankJK


[Markers disappearing_moving  while zooming.zip](https://github.com/mapbox/mapbox-android-demo/files/3168968/Markers.disappearing_moving.while.zooming.zip)

**Comment by LukasPaczos** [comment]
The symbols are disappearing because of the symbol collision detection - in short, if two symbols collide, one is going to be hidden. You can adjust this behavior with `PropertyFactory#iconAllowOverlap` and `PropertyFactory#iconIgnorePlacement` layer properties.

The marker changes the position because it's the center of it that tries to match the desired target. To keep the tip of the marker in place instead, you will need to dynamically adjust the `PropertyFactory#iconOffset` based on the zoom level (`Expression#zoom`), or use a bottom padding on the icon. The other element is `GeoJSON` simplification, which can be adjusted with `GeoJsonOptions#withTolerance` and passed to the `GeoJsonSource` constructor.

Closing as answered. Thanks for using Mapbox and please feel free to reach out to [the support team](https://support.mapbox.com/hc/en-us) or stackoverflow if you have any further questions.
