### ISSUE TITLE
Restore pulsing location example

### ISSUE THREAD

**Issue by yoavrofe** [mapbox/mapbox-android-demo#1060]
The pulsing location example was [removed](https://github.com/mapbox/mapbox-android-demo/pull/424) when Mapbox GL changed to the now-deprecated location plugin. Since location is now included in the main library, I think it'll be nice to restore the example. 
https://github.com/mapbox/mapbox-android-demo/pull/126/files

**Comment by LukasPaczos** [comment]
Hey @yoavrofe, just an FYI that we're working on an integrated feature in https://github.com/mapbox/mapbox-gl-native/pull/13942.

**Comment by langsmith** [comment]
Closing because https://github.com/mapbox/mapbox-gl-native-android/pull/172 landed in the Maps SDK for Android.

Pulsing examples have been added to this app and to Mapbox docs:

https://docs.mapbox.com/android/maps/examples/location-component-basic-pulsing/

https://docs.mapbox.com/android/maps/examples/location-component-custom-pulsing/
