### ISSUE TITLE
Updating data of clustered SymbolLayer

### ISSUE THREAD

**Issue by hansandroid** [mapbox/mapbox-android-demo#1100]
Hello! Tell me, please, is it possible to use clustered SymbolLayer in a project where the data changes dynamically and also need to change the rotation? For example, my attempt to apply this: https://pastebin.com/NwxS6mhJ
This link contains the add / update function, which I occasionally call.
I don’t understand how I can set a rotation to my SymbolLayer and do I update the geodata correctly?

**Comment by langsmith** [comment]
Hi @hansandroid  , thanks for using Mapbox!

`PropertyFactory.iconRotate()` exists and is how you should change a `SymbolLayer` icon's rotation

<img width="575" alt="Screen Shot 2019-06-10 at 7 46 19 AM" src="https://user-images.githubusercontent.com/4394910/59203709-fe822800-8b53-11e9-9135-808cea103f32.png">

To change the data dynamically, get the source and reset the GeoJSON. For example, here's how to update a `CircleLayer`

```java
GeoJsonSource circleSource = style.getSourceAs(CIRCLE_SOURCE_ID);
if (circleSource != null) {
     circleSource.setGeoJson(FeatureCollection.fromFeatures());
}
```

`setGeoJson` is used many times in this demo app: https://github.com/mapbox/mapbox-android-demo/search?l=Java&q=setGeoJson

I'm going to close this issue because this is a question about using Mapbox, rather than a problem with the Android demo app. If you want to continue the conversation about this implementation, please contact the Mapbox support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 and they'll help you out. Thank you!
