### ISSUE TITLE
Get Size of Selected Offline Region Before download in Android

### ISSUE THREAD

**Issue by asifjavaid** [mapbox/mapbox-android-demo#1128]

**Comment by asifjavaid** [comment]
Hi we are using mapbox for our android and iOS apps. We have downloaded the offline regions successfully. We have some couple of questions.

1. How can we get the size of offline map before download?
2. How can we get the size of offline map after download?
3. How can we load the offline map only instead of loading the whole world map?

Thank you.

--
Regards,
Asif Javaid Chughtai
Principal Software Engineer.

**Comment by asifjavaid** [comment]
Hi Guys, do we have any solution to above issues?


Thank you.

**Comment by langsmith** [comment]
Hi @asifjavaid , please see https://docs.mapbox.com/android/maps/overview/offline and https://docs.mapbox.com/android/plugins/overview/offline. There's also the offline section of the plugin test app if you'd like to experiment with offline download/storage: https://github.com/mapbox/mapbox-plugins-android/tree/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/offline

https://docs.mapbox.com/help/interactive-tools/offline-estimator/ is very helpful as well.

I'm going to close this ticket because it's about Mapbox implementation rather than a specific issue with this demo app. If you have further questions, please continue the conversation via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231.
