### ISSUE TITLE
Turn by turn navigation with Multiple way points.

### ISSUE THREAD

**Issue by saddahussain** [mapbox/mapbox-android-demo#1196]
How does turn by turn navigation works with multiple way points?

**Comment by langsmith** [comment]
Hi @saddahussain 

Please see https://docs.mapbox.com/android/navigation/overview/milestones/ and https://docs.mapbox.com/android/navigation/overview/route-progress/.

You might be interested in this pending pr as well: https://github.com/mapbox/mapbox-android-demo/pull/1158 . It uses the Mapbox Directions API response route instead of the full Mapbox Navigation SDK for Android though.

Please contact the Mapbox Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 if you've got more questions.
