### ISSUE TITLE
Add elevation in map android

### ISSUE THREAD

**Issue by asifjavaid** [mapbox/mapbox-android-demo#1244]
Hi,

We are using the following vector layer code to add contour lines in our app.
https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/VectorSourceActivity.java

It is working perfectly.

How can we add elevation data with these contour lines?
We have tried the following code which is not working for us to show elevation data.

```
VectorSource vectorSource = new VectorSource("contour", "mapbox://mapbox.mapbox-terrain-v2");
            style.addSource(vectorSource);

            LineLayer contourLayer = new LineLayer("contour", "contour");
            contourLayer.setSourceLayer("contour");
            contourLayer.setProperties(
                    visibility(Property.VISIBLE),
                    lineJoin(Property.LINE_JOIN_ROUND),
                    lineCap(Property.LINE_CAP_ROUND),
                    lineWidth(1f),
                    lineColor(Color.RED)
            );
            style.addLayer(contourLayer);

            SymbolLayer textLayer = new SymbolLayer("contour-label", "contour")
                    .withProperties(
                            PropertyFactory.textSize(12f),
                            PropertyFactory.textField("{ele}"),
                            PropertyFactory.symbolPlacement(SYMBOL_PLACEMENT_LINE),
                            PropertyFactory.textAllowOverlap(true),
                            PropertyFactory.textColor(Color.BLUE)
                    );

            style.addLayer(textLayer);
```

Thank you.

Regards.
Asif.

**Comment by langsmith** [comment]
If you're talking about querying the elevation at a certain coordinate, there's an example of this at https://docs.mapbox.com/android/java/examples/elevation-query/

**Comment by langsmith** [comment]
Elevation data isn't included Mapbox's Satellite style by default. You could play around with adding a specific dataset to a layer in a custom style.

Here's more information about getting elevation data from Mapbox. 

https://docs.mapbox.com/help/troubleshooting/access-elevation-data/

Because this conversation is about Mapbox implementation, rather than something related to this demo app, please continue this conversation with our formal Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231
