### ISSUE TITLE
how can I make this map Responsive? Means map should open according to number of marker on different position. 

### ISSUE THREAD

**Issue by mitkpatel** [mapbox/mapbox-android-demo#1327]

**Comment by langsmith** [comment]
Hi @mitkpatel , thanks for using Mapbox. 

https://docs.mapbox.com/android/maps/examples/fit-camera-in-bounding-box/ shows how to set camera bounds to show a certain set of coordinates/markers. If you have more questions about this, please contact our support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231. Tickets in this repo are for problems with this app, rather than Mapbox implementation questions.
