### ISSUE TITLE
LocationComponent is under every other layer

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-android-demo#1338]
We are trying to implement the user's location by calling `enableLocationComponen()` as seen in Mapbox Docs. The problem is that we are calling this after the mapbox and its style is loaded. But after this, we will draw symbol layers and lines dynamically on the map, and they are above the user's location marker. We could not find any documentation on how to update the locationMarker to be avobe all layers. Using `LocationComponentOptions.builder(this).layerAbove(layerID)` only works if we call `enableLocationComponen()` after all layers are ready. But since our layers are dynamically changing, we cannot use this. We tried to call it again after the layers got refreshed, but for the 2nd time, the user's location marker did not go above the layers.

Calling `locationComponent.applyStyle()` with an optionsBuilder having `layerAbove()` specified - did not make it go above the layers.

**Comment by langsmith** [comment]
Hey @kiskunk , thanks for using Mapbox. This repo's issue tickets are for specific problems with the app, rather than Mapbox implementation questions. Please contact the excellent Mapbox Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 and they'll get you squared away.
