### ISSUE TITLE
Map not load or not init 

### ISSUE THREAD

**Issue by kjromero** [mapbox/mapbox-android-demo#1356]
Hi guys 

Recently i update version of mapbox in my app.  I was  have used  5.5.3 version. 

Currently  i'm using this version :
![image](https://user-images.githubusercontent.com/11460880/87053523-aa6acc80-c1c7-11ea-85b0-e546e216c9ff.png)

and this is my code 

![image](https://user-images.githubusercontent.com/11460880/87053638-d2f2c680-c1c7-11ea-8ddb-0c3b71471ae6.png)

![image](https://user-images.githubusercontent.com/11460880/87053768-f7e73980-c1c7-11ea-9eae-830f10398521.png)

but this not work, the map is displayed like this

![image](https://user-images.githubusercontent.com/11460880/87054078-53192c00-c1c8-11ea-8dd6-7b07fa163c61.png)

this is my XML

![image](https://user-images.githubusercontent.com/11460880/87054259-852a8e00-c1c8-11ea-86a2-da1a51a182db.png)

thanks for your help

**Comment by langsmith** [comment]
Thanks for using Mapbox, @kjromero . Issue tickets in this repo are for specific problems with this app, rather than Mapbox implementation questions. 

Please contact our Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 to get help with your specific question(s).

**Comment by kjromero** [comment]
hi @langsmith ,
This problem is into a fragment. The mapbox not show into a fragment.

This issue not is about implementation, my app has have use Mapbox around of 3 years ago. 
But when i try upgrade the mapbox version, this not work for my
