### ISSUE TITLE
Stright arrow line with information between two location

### ISSUE THREAD

**Issue by umeshkanhasoft** [mapbox/mapbox-android-demo#1363]
can you help me please how to draw stright arrow line with information between two location?

**Comment by langsmith** [comment]
Thanks for using Mapbox, @umeshkanhasoft . Tickets in the repo are for issues with this app, rather than Mapbox implementation questions.

You'll want to use a LineLayer (https://github.com/mapbox/mapbox-android-demo/search?q=LineLayer&unscoped_q=LineLayer) for the line and a `SymbolLayer` at one end of the line to represent the arrowhead. Not sure what you mean `with information between two location`.

You might find your answer in https://stackoverflow.com/questions/tagged/mapbox. Another option is to contact the Mapbox Support team to continue the conversation and continue your questions. The team can be reached via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231.

**Comment by langsmith** [comment]
https://stackoverflow.com/search?q=%5Bmapbox%5D+arrow and https://stackoverflow.com/questions/54409187/how-to-draw-arrows-with-mapbox/
