### ISSUE TITLE
How to loadassest of my own geojson files?

### ISSUE THREAD

**Issue by teowks000** [mapbox/mapbox-android-demo#1367]

**Comment by langsmith** [comment]
This app uses ` LoadGeoJson extends AsyncTask` to load from a local asset file.

https://github.com/mapbox/mapbox-android-demo/search?q=loadGeojson&unscoped_q=loadGeojson

**Comment by teowks000** [comment]
Hello friend thank you for your reply, but the problem I'm experiencing now
is I have multiple geojson file like 8 of them may I know how should I load
8 of them into my android app? Should I just LoadGeoJson 8 times?

**Comment by langsmith** [comment]
You could include them all with your app and then load the correct file at the correct time. Or would you be loading all 8 files at once?

You could upload the GeoJSON to https://studio.mapbox.com/tilesets/ and create tilesets and then reference each tileset as a `VectorSource`. See https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/VectorSourceActivity.java to see how to use a `VectorSource`.

You could upload all of the GeoJSON to a single dataset via https://studio.mapbox.com/datasets and then export the dataset as a single tileset.

Once the GeoJSON is in a tileset format, you could also include the data in a custom Mapbox style via Mapbox Studio at https://studio.mapbox.com. When you load the style on the Android device, the data will appear because it's already a part of the style.
