### ISSUE TITLE
'within(polygon)' Not working correctly for VectorSource

### ISSUE THREAD

**Issue by mattRippin** [mapbox/mapbox-android-demo#1385]
Hey,

I've attempted to implement 'within(polygon)' for my mapbox map. using the following process:

I set up my vector source: 

```
val tileset = TileSet("2.1.0", "custom_super_cool_vector_source_url")
val vectorSource = VectorSource(VECTOR_SOURCE_ID, tileset)
style?.addSource(vectorSource)
```

Then I add my layer:

```
fun makeMyLayer(polygon: Polygon){
        val someCircleLayer = CircleLayer(LAYER_ID, VECTOR_SOURCE_ID)
        someCircleLayer.sourceLayer = "geojsonLayer"
        someCircleLayer.setProperties(
                circleColor(Color.TRANSPARENT),
                circleRadius(25f),
                iconAllowOverlap(true),
                iconIgnorePlacement(true)
        )
        someCircleLayer.setFilter(
                within(polygon)
        )
        mapBoxReference?.style?.addLayer(someCircleLayer)
    }
```

This basically does nothing. All my features show up as normal, no filtering is applied.

Can someone please assist. 

Thanks!

@langsmith

**Comment by langsmith** [comment]
Anything from the Maps SDK in your logcat? Search for `Mbgl`. When I apply `iconAllowOverlap(true),` and `iconIgnorePlacement(true)` to a `CircleLayer` in a demo app example, I get 👇 

<img width="755" alt="Screen Shot 2020-10-09 at 1 20 58 PM" src="https://user-images.githubusercontent.com/4394910/95628179-5ffd2400-0a32-11eb-8152-8b2f90e08b35.png">

What happens if you remove these two?

**Comment by mattRippin** [comment]
Good catch! I've exchanged it for a different layer with the following configuration and I'm still seeing nothing. Below the code block is what I'm seeing for MBGL logs:

```
    private fun makeMyOtherLayer(polygon: Any) {
        val symLayer = SymbolLayer(MY_OTHER_LAYER_ID, VECTOR_SOURCE_ID)
        symLayer.sourceLayer = "geojsonLayer"

        symLayer.withProperties(
                iconImage(NEW_LISTING_BLUE_CIRCLE),
                iconSize(0.5f)
        )

        symLayer.setFilter(
                within(polygon as Polygon)
        )

        mapBoxReference?.style?.addLayer(symLayer)
    }
```
![Screen Shot 2020-10-09 at 4 56 07 PM](https://user-images.githubusercontent.com/71451760/95630788-71edbf80-0a50-11eb-9b5b-5fce9a7d13cc.png)

**Comment by langsmith** [comment]
> I'm still seeing nothing

Can you say more about ☝️ ? No data is being shown _at all_ in the layer? Or it's just that the filter logic isn't being applied?

What is `mapBoxReference`? A `MapboxMap` object? If so, as a matter of best practice and so that you don't need the null check `?` after `style`, you could use the `onStyleLoadedCallback()` to be safe:

```kotlin
                mapBoxReference?.getStyle {
                    it.addLayer(symLayer)
                }
```

**Comment by mattRippin** [comment]
Started over with a whole new project and it seems to work now. Not really sure what's going on, but it's workin as intended. Thanks for your quick replies @langsmith.

**Comment by langsmith** [comment]
Hm, weird. Ok, glad it's working. Thanks for using Mapbox!
