### ISSUE TITLE
Add labs example showing how to create indoor map

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#147]
The style API should make this possible now using a similar method to how I previously did it with the old SDK. 

cc: @zugaldia

**Comment by cammace** [comment]
Here's what I have so far:

![ezgif com-video-to-gif 9](https://cloud.githubusercontent.com/assets/5652865/18852600/2b6223d8-840f-11e6-81eb-7cf600714288.gif)

Things that still need to be done:
- [ ] Show a multistory building with UI to toggle between them
- [ ] Room number/name labels

**Comment by npitcher** [comment]
This is a great candidate for the blog once it's ready. per chat with @cammace, we'll need to ship update 4.2.0 first before it can be blogged. Timeline on that update is late October. 

@jenyuhk flagging for you - we had interest in this feature at [DevFestDC](https://github.com/mapbox/business/issues/3417#issuecomment-249896686). @cammace can you be point person on getting this into the blog pipeline? You'll want to cut a ticket in /blog repo with ticket title including target merge date.

**Comment by ErinQuinn** [comment]
Can't wait to send this out to folks who write in about indoor mapping - looks great @cammace !

**Comment by zugaldia** [comment]
Just noting here that this example will require us to set the right expectations. In particular, that this is not (yet) a full replacement for the indoor APIs that Google provides on Android (e.g. [`IndoorBuilding`](https://developers.google.com/android/reference/com/google/android/gms/maps/model/IndoorBuilding)). Instead this is one more example of how the Runtime Style API enables developers to do pretty much anything they want with the map, like start building indoor experiences.

**Comment by cammace** [comment]
I've now changed the location of the indoor map to the White house along with made the floor level buttons only display when the user is hovering over the indoor map area, otherwise the fade out.

![ezgif com-video-to-gif 7](https://cloud.githubusercontent.com/assets/5652865/19744263/b262b030-9b9a-11e6-828f-85dabd8e0efd.gif)

Next step will be to add the second story GeoJSON file.

**Comment by cammace** [comment]
Indoor map example has been merged.

**Comment by phfeitosaa** [comment]
Hey Cammace!

How could i use sdk navigation to create a navigation inside an indoor map? Let me explain better, I need to create a navigation application for internal locations that shows the route and navigates from one place to another. To make the location of the user without using the gps, I will use qr codes scattered throughout the building to give me the exact location of the user and then show the route and make the navigation to the destination. But I'm not sure if it's possible to do this using the mapbox, since it's geared towards external applications.
I would be grateful if anyone could help me.

**Comment by zugaldia** [comment]
@phfeitosaa Thanks for the question and for trying the Navigation SDK. We're using this repository and its issues to track problems with the Mapbox demo app. For general support questions, please [contact support](https://www.mapbox.com/contact/support/).

**Comment by Sadmansamee** [comment]
But how do I create indoor GeoJson? I have no clue

**Comment by langsmith** [comment]
hey @Sadmansamee , thanks for looking into Mapbox. The answer kind of depends on what you mean by `indoor GeoJSon`. You can still use Mapbox to create floor layout information as seen in https://github.com/mapbox/mapbox-android-demo/issues/147#issuecomment-256470058 ([example code here](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/IndoorMapActivity.java)).  There's also [Indoor3DMapActivity](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/Indoor3DMapActivity.java). You can use `FillLayer` and `LineLayer`s to mark various indoor areas.

[Mapwize](https://www.mapwize.io/) is a full platform (which uses Mapbox) for more custom indoor information
https://blog.mapbox.com/indoor-maps-with-mapwize-ef645fe50eb4

**Comment by Sadmansamee** [comment]
@langsmith I think Mapwize is great but it's a bit too pricey for our need, another question we add navigation between places?

**Comment by langsmith** [comment]
@Sadmansamee , I'm going to direct you to our awesome Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 so that you can continue the conversation with them. It'll be a better avenue than back-and-forth on this ticket.

They'll be able to chat with you about your end goal(s) and what options you have with the flexible Mapbox platform.
