### ISSUE TITLE
Mirror flip problem

### ISSUE THREAD

**Issue by mister-tang** [mapbox/mapbox-android-demo#233]
Hud need to flip effect, I set the
  mapView.setScaleY(-1);

MapView flipped over, but the drawing of the route did not show up, using the method is map.addPolyline ()

MapView uses SurfaceView? How to set up to show the normal route, thank you

**Comment by mister-tang** [comment]
Now I have tried mapView.setRotation (180). Find the map all show black

**Comment by cammace** [comment]
You can try enabling texture view [in XML](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml#L76) and flip the view. Otherwise, this is not the appropriate repo for questions and rather meant for the demo app exclusively. Please try posting in GL-Native if you are still having issues.

**Comment by mickokenter** [comment]
> Hud need to flip effect, I set the
> mapView.setScaleY(-1);
> 
> MapView flipped over, but the drawing of the route did not show up, using the method is map.addPolyline ()
> 
> MapView uses SurfaceView? How to set up to show the normal route, thank you

Hi mister-tang,

May I ask that have you solved this problem? I want to do the same thing.

Best,
Matthew

**Comment by mister-tang** [comment]
> > Hud need to flip effect, I set the
> > mapView.setScaleY(-1);
> > MapView flipped over, but the drawing of the route did not show up, using the method is map.addPolyline ()
> > MapView uses SurfaceView? How to set up to show the normal route, thank you
> 
> Hi mister-tang,
> 
> May I ask that have you solved this problem? I want to do the same thing.
> 
> Best,
> Matthew

solved！
