### ISSUE TITLE
Unsatisfied link error

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#259]
```
Exception java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mapbox.mapboxandroiddemo.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo.debug-2/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libmapbox-gl.so"
java.lang.Runtime.loadLibrary0 (Runtime.java:984)
java.lang.System.loadLibrary (System.java:1530)
com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit> (NativeConnectivityListener.java:9)
com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance (ConnectivityReceiver.java:34)
com.mapbox.mapboxsdk.Mapbox.getInstance (Mapbox.java:41)
com.mapbox.mapboxandroiddemo.testing.EditablePolygonActivity.onCreate (EditablePolygonActivity.kt:73)
android.app.Activity.performCreate (Activity.java:6679)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1118)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2618)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2726)
android.app.ActivityThread.-wrap12 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1477)
```

**Comment by tobrun** [comment]
-> outdated version on Firebase, not seen this with current production version.

**Comment by ArLabDev** [comment]
@Tobrun, please could you better explain relationship of this crash with Firebase?
I have the same crash on my App (I cannot replicate it) but I have about 50 crash reports in firebase, the last of december 2017.
All reports on API 23 and on few devices (quite uncommon: FEVER, CUBOT, Acer T11 and other four)

I use mapboxsdk 5.1.3 and Firebase 11.4.0.
To reduce .apk size I support only 32 bit ABI (x86 and armeabi-v7a)

What I understand from the Exception is that it's trying to find a 64 bit native library, but it does not find it. It's quite strange, because all devices reporting the crash supports armeabi-v7a and so they should load it.
I tested the App with several devices, boht x86 and Arm and it seems to work fine (except that on few devices that I do not have to test on)

Thanks
