### ISSUE TITLE
Update Play Store and Readme images

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#295]
with the new colors and design our images have become outdated, we should update them in the play store and readme file here. The Google Play Store icons also need to be updated to reflect the changes.

cc: @langsmith

**Comment by langsmith** [comment]
@cammace , adding this ticket to this repo's 5.1.0 milestone. I'll do screenshots and updating once we're done and confident that new branding UI is finished. Who has the original (Sketch) file for editing for the repo's readme header image? You? @mayagao ?

**Comment by cammace** [comment]
I'll share with you @langsmith.

**Comment by langsmith** [comment]
Fixed with https://github.com/mapbox/mapbox-android-demo/pull/309

I don't know whether you or @tobrun have Play Store access, but here are the images for updating in the developer console...
 
![device-2017-05-01-093728](https://cloud.githubusercontent.com/assets/4394910/25585927/fcd2e3b6-2e6a-11e7-86ca-3bf57940b82d.png)

![device-2017-05-01-094022](https://cloud.githubusercontent.com/assets/4394910/25586021/641e3ef8-2e6b-11e7-8a42-645b5affcdca.png)

![device-2017-05-01-093907](https://cloud.githubusercontent.com/assets/4394910/25585985/3833b868-2e6b-11e7-8a7f-aece5419bae1.png)


![device-2017-05-01-093805](https://cloud.githubusercontent.com/assets/4394910/25585956/118caeb8-2e6b-11e7-85ec-62bd4d3b48b8.png)
