### ISSUE TITLE
how to add map label

### ISSUE THREAD

**Issue by snailTomato** [mapbox/mapbox-android-demo#308]
Im using mapbox to show  indoor map(by load geojson source ). It seems that it can only draw the vetcor indoor building. How can i show map label(such ad text label: room101) on my indoor map?  thank you!  Im looking forward your replay.

**Comment by cammace** [comment]
You should have a look at the symbol layer example in this [demo repo](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java) which can easily be converted to display text instead of icons. When creating the GeoJSON source, add the room numbers as a properties field and then you can correctly place them on the map. 

In the future, try reaching out to us either on Stack Overflow or using our [contact page](https://www.mapbox.com/contact/).

**Comment by snailTomato** [comment]
thank you! I am a  greenhand. I can use `    SymbolLayer markers = new SymbolLayer("marker-layer", "marker-source").withProperties(PropertyFactory.textField("aaa"));`  replace icon to "aaa". But, i don't understand how to " creating the GeoJSON source, add the room numbers as a properties field ". Can you give me more tips. Thanks.

**Comment by cammace** [comment]
You might actually find [this example](https://github.com/mapbox/mapbox-java/blob/master/mapbox/app/src/main/java/com/mapbox/services/android/testapp/distance/DistanceActivity.java) in our testapp even more useful, it actually does what I described above. Hope this helps! In the future, opening these questions on Stack Overflow typically helps others quickly find the same solutions to this issue :)

**Comment by snailTomato** [comment]
thanks！ It really helpful. I would like to share this answer on Stack Overflow to help others!
