### ISSUE TITLE
3d-extrusions Adjust the light position

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-android-demo#317]
Simulate a sunrise/sunset by adjusting the map light position similar to what is shown at the bottom of [this blog post](https://www.mapbox.com/blog/shading-lighting-3d-features/).

**Comment by 1ec5** [comment]
Blocked by mapbox/mapbox-gl-native#8841.

**Comment by langsmith** [comment]
@cammace , because of https://github.com/mapbox/mapbox-gl-native/issues/8841 blocking it, I'm going to remove this from the 5.1.0 milestone

**Comment by 1ec5** [comment]
mapbox/mapbox-gl-native#8841 is still scheduled for v5.1.0 of the SDK (and would probably be a release blocker in any case).

**Comment by langsmith** [comment]
@tobrun made a light adjustment example in the sdk test app. [I added it to the demo app.](https://github.com/mapbox/mapbox-android-demo/pull/363).

Do we feel that it's close enough to the blog post example that @cammace linked to at the top of this ticket? Or should this ticket stay open because we could stand to a separate example that allows the user to drag the light point around a globe or something?...

**Comment by cammace** [comment]
Depends on if the examples show different APIs or not. I'd lean more towards having one example or the other but if we are showing two completely different features, both examples could be added.

**Comment by langsmith** [comment]
I agree that it'd be overkill to have two separate examples. 

The current one in the demo app adequately shows light direction, intensity, and color.
