### ISSUE TITLE
Places details and nearby placesn not found : HELP ME

### ISSUE THREAD

**Issue by niravkhunt** [mapbox/mapbox-android-demo#466]
This is awesome demo . But some features like places details and near by places like atm , bank , etc not here. Google has awesome apis so i want to check whether these features are available in mapbox ?

Please do needful if you have idea about this .

**Comment by langsmith** [comment]
Hi @niravkhunt ,

Thank you very much for your interest in Mapbox. I'm not sure what you want to use ATM/Bank/etc. information for, but you should know that we offer [Geocoding](https://www.mapbox.com/geocoding/) and there's [a geocoding example in the Android demo app](https://github.com/mapbox/mapbox-android-demo/blob/eadaf3a81c01f1390753dbe24b560f77d117ec27/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/mas/GeocodingActivity.java). 

There's also [a feature query example](https://github.com/mapbox/mapbox-android-demo/blob/eadaf3a81c01f1390753dbe24b560f77d117ec27/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/QueryFeatureActivity.java) that is along the lines of your original ticket

Please [contact sales](https://www.mapbox.com/contact/sales/) and/or [contact support ](https://www.mapbox.com/contact/support/) if you have more questions about Mapbox's capabilities and how to include Mapbox into your project(s).

Closing this ticket because there's no problem with the app.

**Comment by Lokkeshss** [comment]
Hi Team,
We are planning to develop cyclic app where user's can search nearby coffee shop or nearby restaurant from user current location at the time of ride. So far I searched I could not find the code.
Is their any reference so that I can use it of
