### ISSUE TITLE
Count invisible markers

### ISSUE THREAD

**Issue by lashket** [mapbox/mapbox-android-demo#475]
according this [example]( https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java)
when i'm zooming out a map, some markers become invisible.
Is there way to find count of invisible markers?

**Comment by langsmith** [comment]
Hey @lashket ,

What are you trying to achieve by finding the non-displayed markers? I ask because perhaps there's an easy way to accomplish it...

**Comment by lashket** [comment]
@langsmith i wan to show a message like "Zoom in to see 10 markers", or only "Zoom in to see more markers". And for this, i need to know are there invisible markers or no

**Comment by lashket** [comment]
@langsmith i wan to show a message like "Zoom in to see 10 markers", or only "Zoom in to see more markers". And for this, i need to know are there invisible markers or no

**Comment by langsmith** [comment]
Hey @lashket , sorry that I'm finally getting back to you about this.

`queryRenderedFeatures()` ([example here](https://github.com/mapbox/mapbox-android-demo/blob/eadaf3a81c01f1390753dbe24b560f77d117ec27/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/QueryFeatureActivity.java#L56)) already counts features that would be displayed (according to the style) but end up getting collided out. If that's the case, then there isn't currently a way to come up with the count that you want. For now, my best suggestion is for you to look into clustering instead. [The demo app's clustering example](https://github.com/mapbox/mapbox-android-demo/blob/eadaf3a81c01f1390753dbe24b560f77d117ec27/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/GeoJsonClusteringActivity.java) Showing the clustered marker count would also save you precious space on the screen so that you don't have to have a toast/snackbar/banner/etc. that says "Zoom in to see XX markers"

Fyi, `iconAllowOverlap(false)`, makes the map not hide the symbols. Might be interesting to see what that does to your UX/UI...
