### ISSUE TITLE
Markers display not good

### ISSUE THREAD

**Issue by limboc** [mapbox/mapbox-android-demo#489]
[img](http://ipsmap.oss-cn-shanghai.aliyuncs.com/WechatIMG29.jpeg)
android sdkVersion:5.1.3
according this [example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/annotations/CustomInfoWindowActivity.java)
I used custom InfoWindowAdpter
When I zoom in and out a few times, it goes like this

**Comment by langsmith** [comment]
Thanks for the note @limboc . Are you willing to share any code snippets that might be helpful? Make a GIF/video to show me what's actually happening on your screen as you zoom in and out?

**Comment by limboc** [comment]
the same problem as [#9910](https://github.com/mapbox/mapbox-gl-native/issues/9910)

**Comment by langsmith** [comment]
Thanks @limboc . I'm going to close this in favor of [#9910](https://github.com/mapbox/mapbox-gl-native/issues/9910), in part because this issue isn't an issue with the demo app itself. Also see:

[#8943](https://github.com/mapbox/mapbox-gl-native/issues/8943) and [#9026](https://github.com/mapbox/mapbox-gl-native/issues/9026)
