### ISSUE TITLE
Question :: Does mapbox android sdk support clustering??????

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-android-demo#553]
Can anyone please let me know, is there any way to achieve clustering with mapBox sdk, as I need to plot different markers (approx 1000+ )and need to show as clusters.

Thanks, Any help really appreciate.

**Comment by langsmith** [comment]
@mf-mindcrewtech , we've got a marker cluster plugin for Android. The documentation isn't quite published yet, which is why you hadn't known about it.

Here's the upcoming README about it:
[https://github.com/mapbox/mapbox-plugins-android/blob/e31b6bbb51a806f48a75ada970d2039405349a55/plugin-cluster/README.md](https://github.com/mapbox/mapbox-plugins-android/blob/e31b6bbb51a806f48a75ada970d2039405349a55/plugin-cluster/README.md)

Upcoming Android demo app marker cluster plugin example: [https://github.com/mapbox/mapbox-android-demo/blob/f05feea9599aee09df69589cf9c840dd356e62df/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/MarkerClustersPluginActivity.java](https://github.com/mapbox/mapbox-android-demo/blob/f05feea9599aee09df69589cf9c840dd356e62df/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/MarkerClustersPluginActivity.java)

[Current marker cluster plugin code](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-cluster)

Thanks for using Mapbox!

**Comment by mf-mindcrewtech** [comment]
Hi @langsmith , thanks for the reply, yupp thats working fine. Appreciate your help.

Can you please tell me how can I add my custom icon and also the custom info window with ClusterManagerPlugin.

NOTE :: I am very much familiar with adding custom icon and info window but without clustering.
