### ISSUE TITLE
Question :: How to change marker icon with ClusterManagerPlugin

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-android-demo#556]
Hi all , 

Can anyone please tell me how can I add my custom icon with ClusterManagerPlugin.

NOTE :: I am very much familiar with adding custom icon and info window but without clustering.

**Comment by langsmith** [comment]
@mf-mindcrewtech , you're asking how to change the icon(s) that are used for the clusters? Instead of the colored circles that the plugin currently uses? If so, there's currently no _built-in_ ability to change them. The plugin was just recently released and we haven't gotten around to adding more customization. There other customization that I'm personally interested in is being able to change the colors of the cluster circles, so that the clustering matches the look of the app/map/brand. 

We do welcome pull requests if you'd like to give things a shot yourself 😉 

Thanks for your patience...

cc @tobrun

**Comment by mf-mindcrewtech** [comment]
Hi @langsmith , I didn't mean to change the circle's color, what I want to change the red default icon, I want to replace with my custom icon.

I know how to achieve without clustering, but i don't know how to achieve with clustering.

**Comment by langsmith** [comment]
There's currently no way to change the cluster icon. The plugin was just recently released and we haven't gotten around to adding more customization.

**Comment by marconealberto** [comment]
are there updates on this? I need to customize the icon of the pins inside the cluster.

**Comment by mf-mindcrewtech** [comment]
@langsmith yupp I done the custom icons with clustering, I will send the pull requests for sure. So everyone with get the same features. ;)

**Comment by marconealberto** [comment]
oh, please, that would be great! I don't really have time to look into it and found this out at the last minute!

**Comment by mf-mindcrewtech** [comment]
@marconealberto Okay I will create a demo project with custom icons by tomorrow and share the link with you

**Comment by dawnithan** [comment]
@mf-mindcrewtech hi, do you still have this project/solution and could you share it? thanks

**Comment by mf-mindcrewtech** [comment]
Hi @dawnithan , Yupp I am still having solution, Do you want me create a demo and share it here or it would be good if you contact me on Skype .

My Skype ID :: maroofahmedsiddique

**Comment by dawnithan** [comment]
Here on GitHub would be great
