### ISSUE TITLE
One of setGitDir or setWorkTree must be called.

### ISSUE THREAD

**Issue by zhangxiaobin123456** [mapbox/mapbox-android-demo#599]
i'm download this demo,but it has an exception,can you call me how to do?

![question](https://user-images.githubusercontent.com/17853034/34868303-4075902e-f7be-11e7-866e-060b02f36cc1.png)

**Comment by langsmith** [comment]
Hi @zhangxiaobin123456 , I've never seen that error before. Try this –> https://github.com/tomahawk-player/tomahawk-android/issues/67#issuecomment-270845544  and let me know if you still have the error?

**Comment by zhangxiaobin123456** [comment]
I have use  "git clone url " download this demo and it not have the error.thanks

**Comment by langsmith** [comment]
🎉 🍾 🎆   Glad to hear it @zhangxiaobin123456

**Comment by Kyle-Falconer** [comment]
This issue still persists when downloading the project as a zip.

This should really be fixed.

**Comment by langsmith** [comment]
Looking into this now. Thanks for your patience everyone. Confirmed that I get this error when I download the repo's .zip folder and try to open the project.


![screen shot 2018-04-27 at 10 33 37 am](https://user-images.githubusercontent.com/4394910/39376427-858d800a-4a06-11e8-98d6-c360c7153bd1.png)

**Comment by langsmith** [comment]
That happens when you're not building it in a git clone directory. The build looks for for the .git subdirectory because it uses repository history to assign version numbers and to communicate with github for doing releases. _I would just download the project via command line git_ 

`git clone https://github.com/mapbox/mapbox-android-demo.git`

**Comment by Kyle-Falconer** [comment]
> because it uses repository history to assign version numbers and to communicate with github for doing releases.

This shouldn't be *required* except if you're trying to contribute code changes or build a release. In the build.gradle file, this should check to see if the .git folder is present and if not, use some arbitrary value for the version number.

**Comment by tobrun** [comment]
@langsmith googled the error message and the issue seems to come from grgit. 
We use that library as part of grade-git library as seen [here](https://github.com/mapbox/mapbox-android-demo/blob/master/gradle/script-git-version.gradle). 
To fix this issue please update https://github.com/mapbox/mapbox-android-demo/blob/master/gradle/script-git-version.gradle#L8 to the latest stable version.

**Comment by gpolic** [comment]
I tried to build the app from the zip file. It was a little bit of pain
In the end it was built when I changed the file script-git-version.gradle, to :

```
// https://hackernoon.com/configuring-android-project-version-name-code-b168952f3323#.fcoiok3lv

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.ajoberstar:grgit:1.5.0'
    }
}

/**
 * git.describe()
 *
 * Find the most recent tag that is reachable from HEAD. If the tag points to the commit,
 * then only the tag is shown. Otherwise, it suffixes the tag name with the number of additional
 * commits on top of the tagged object and the abbreviated object name of the most recent commit.
 *
 * More info: https://git-scm.com/docs/git-describe
 */

ext {

    gitVersionName = "1.0"
    gitVersionCode = 2
    gitVersionCodeTime = 1484407970
}
```

**Comment by langsmith** [comment]
thanks @gpolic. That has helped me in https://github.com/mapbox/mapbox-android-demo/pull/786. Adding something similar to https://github.com/mapbox/mapbox-android-demo/pull/786 has enabled me to cleanly build/install the app after downloading that branch's `.zip` folder.
