### ISSUE TITLE
Some bugs happened when add markers

### ISSUE THREAD

**Issue by zhuxixiang** [mapbox/mapbox-android-demo#755]
There were some bugs, when I added markers on my map (using my own custom bitmap):
1. I have to touch on the map or `easeCamera`  (`mapview.requestLayout()` and `mapview.invalidate()` is also not working), before it shows at the first time.
2. Sometimes, markers were just gone when I dragged or pinched on the map. Only drag can cause it, even in the same zoom.
3. Sometimes, the marker is showing but can‘t be clicked...

Env:Android 8.0, mapbox 6.1.3

My Code：
```
public MarkerView addMarker(Bitmap bitmap, MapPoint position, float xOffset, float yOffset) {
        if (mMapboxMap != null && bitmap != null && position != null) {
            MarkerView markerView = mMapboxMap.addMarker(new MyBaseMarkerOptions()
                    .position(position.toMapBox())
                    .anchor(xOffset, yOffset)
                    .icon(IconFactory.getInstance(this).fromBitmap(bitmap))
                    .visible(true)
            );
            mMapboxMap.selectMarker(markerView);
            updateMapCenter(mMapboxMap.getCameraPosition().target);
            return markerView;
        }
        return null;
    }
```
the reasons of using MarkerView:
1. I could not find offset in Marker
2. I could not bring the marker to the front when click

**Comment by langsmith** [comment]
Hi @zhuxixiang , thank you for using Mapbox. We really appreciate it.

I'd encourage you to use `SymbolLayer` and icons instead of Marker/Markerview. 

https://www.mapbox.com/android-docs/map-sdk/overview/annotations/#source-and-layer

Helpful spots in the demo app:
- https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/InfoWindowSymbolLayerActivity.java#L120-L124
- https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/InfoWindowSymbolLayerActivity.java#L172-L194
- icon offset: https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/InfoWindowSymbolLayerActivity.java#L164-L165

This ticket isn't an actual issue with this demo app, so I'm going to close this ticket. If you'd like to continue a conversation about your specific questions, please use the form at https://www.mapbox.com/contact/support/#products/android
