### ISSUE TITLE
Efficient way of adding multiple RasterSource and RasterLayers to mapbox map

### ISSUE THREAD

**Issue by ferily7** [mapbox/mapbox-android-demo#776]
I'm adding multiple layers to map, but the code is really redundant and I know I'll run into problems when I have to add 10+ layers since I have to write the same code multiple times. Here is how my code looks like at the moment:

```
RasterSource sourceName = new RasterSource("source-id",
                new TileSet("tileset", "http://websitename.com/v4/tileset-name/{z}/{x}/{y}.png"), 256
        );

mapboxMap.addSource(sourceName );

// Adding the layer to the map
RasterLayer layerName= new RasterLayer("layer-id", "source-id");
mapboxMap.addLayer(layerName);
```

I'm wondering if there is a way to add 10 layers to the map in an efficient way? Is there any feature where you can add multiple layers or does mapbox simply doesn't have anything like this? I just wanted to ask out of curiosity!

**Comment by langsmith** [comment]
Hey @ferily7 , thanks for using Mapbox! I think a `for` loop is the best way to add your layers in this case. Based on your code above, I'm not sure what parts of your source/layer setup will remain the same vs. what you want to change for each layer added to the map. 

A `for` loop is used in a demo app example here: https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/GeoJsonClusteringActivity.java#L184-L190 and https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/GeoJsonClusteringActivity.java#L204 . 

**So**, for you, it would look like:

```java
RasterSource sourceName = new RasterSource("source-id",
      new TileSet("tileset", "http://websitename.com/v4/tileset-name/{z}/{x}/{y}.png"), 256
    );
    mapboxMap.addSource(sourceName);
    
    for (int x = 0; x < 10; x++) {
      RasterLayer layerName = new RasterLayer("layer-id-" + x, "source-id");
      mapboxMap.addLayer(layerName);
    }
```

You'd just have to add your single RasterSource to the map (like you've done above). Then use the `for` loop to create a `RasterLayer` , a unique id for the `RasterLayer`, and add it to the map. You won't need to change `source-id` because you want each `RasterLayer` to reference the same `RasterSource` data. 

How does this sound/look?

**Comment by ferily7** [comment]
Hi @langsmith, I'm not quite sure if this method would quite work for me because I'll be adding multiple RasterSource to the mapboxMap and to add that to the map as a layer, you would need a distinct source-id? My problem arises in that I will have 10+ declarations of the following code:

```
RasterSource sourceName = new RasterSource("source-id",
      new TileSet("tileset", "http://websitename.com/v4/tileset-name/{z}/{x}/{y}.png"), 256
    );
    mapboxMap.addSource(sourceName);
```
Since I'm trying to add a different tilesets. And then I'll be creating a RasterLayer and adding that to the mapboxMap. Let me know if I misunderstood what you said!

**Comment by langsmith** [comment]
@ferily7 , you could try something along the lines of 👇 Make separate arrays for the loop to digest and fill in the `z,`x`, and `y` values in your raster tile URL. I just chose `4, 5, 6, 7, 8` as placeholders. All of your source and layer ids would be unique but also match accordingly

```java
int[] zArray = new int[] {4, 5, 6, 7, 8};
int[] xArray = new int[] {4, 5, 6, 7, 8};
int[] yArray = new int[] {4, 5, 6, 7, 8};

for (int x = 0; x < 10; x++) {
    RasterSource sourceName = new RasterSource("source-id-" + x, new TileSet("tileset",
    String.format("http://websitename.com/v4/tileset-name/%f/%f/%f.png", zArray[x], xArray[x], yArray[x])), 256);

    mapboxMap.addSource(sourceName);

    RasterLayer** layerName = new RasterLayer("layer-id-" + x, "source-id-" + x);
    mapboxMap.addLayer(layerName);
}
```

You could make 
```java
RasterSource sourceName = new RasterSource("source-id",
      new TileSet("tileset", "http://websitename.com/v4/tileset-name/{z}/{x}/{y}.png"), 256
    );
    mapboxMap.addSource(sourceName);
```
into a method with the `z`,`x`, and `y` values the method parameters. Then just run the method 10 times or whatever while passing in the appropriate parameter values that you want for the your RasterSource

```java
addRasterSource()

**Comment by langsmith** [comment]
Closing this 'cause I haven't heard back. More than happy to continue the discussion though.
