### ISSUE TITLE
Cluster marker click

### ISSUE THREAD

**Issue by TooLazyy** [mapbox/mapbox-android-demo#873]
Hi. There is in demo app an example with clustering from geojson remote source.
If i add map marker on the map like:
`mapboxMap?.addMarker(MarkerOption())` i can handle marker click and show `InfoWindow`.
The question is: can i get the same behavior with clustering? I mean handle cluster item click and show `InfoWindow` system way? Or its all about custom workaround?

**Comment by langsmith** [comment]
Hey @TooLazyy , thanks for using Mapbox! It'll be some sort of custom workaround at this point. To confirm, you want to show an info window when a cluster item is selected. For example, when one of the yellow triangles is tapped on?

![42000304-1db0f48c-7a15-11e8-95b1-29d1c7cf68f8](https://user-images.githubusercontent.com/4394910/46757127-13818100-cc7e-11e8-84df-1c3692e581ed.gif)

**Comment by TooLazyy** [comment]
Hi. thanks for reply.
I meant unclustered item click.
But i'm already managed to do this)

**Comment by langsmith** [comment]
Ah, ok.

**Comment by InvictusGar** [comment]
> Hey @TooLazyy , thanks for using Mapbox! It'll be some sort of custom workaround at this point. To confirm, you want to show an info window when a cluster item is selected. For example, when one of the yellow triangles is tapped on?
> 
> ![42000304-1db0f48c-7a15-11e8-95b1-29d1c7cf68f8](https://user-images.githubusercontent.com/4394910/46757127-13818100-cc7e-11e8-84df-1c3692e581ed.gif)

hi, how could I do something when a cluster item is selected?

**Comment by InvictusGar** [comment]
@langsmith

**Comment by langsmith** [comment]
> how could I do something

What would you like to have happen?

**Comment by InvictusGar** [comment]
@langsmith I've already solve the problem by using queryRenderedFeatures.

and now, I have another problem which is :

Is there any way to custom the icon of clusters, each cluster feature has one different icon-image?

I'm using cluster in Android and set every feature with the property of "icon"
and then I can add the source and layer with .withProperties(iconImage("{icon}"))

after that every point in unclustered layer can get the property of icon
but when I zoom in and the map clusters, I found that the cluster layer's feature only has the properties of "point_count_abbreviated" ,"point_count" , "cluster_id" , "cluster", "icon" got lost.

So is there any method to keep the "icon" property in the cluster layer?

**Comment by lwuu0021** [comment]
Hi @TooLazyy @langsmith, 
I'm developing the same feature with a map having clustering effect and an info window on a single marker. 
I tried to combine these two demo:

https://docs.mapbox.com/android/maps/overview/clustering/
https://docs.mapbox.com/android/maps/examples/symbol-layer-info-window/

However, data clustering is working well.
But I couldn't use the info window working as demo. 

![image](https://user-images.githubusercontent.com/70126797/93749689-ad5d5100-fc3d-11ea-8bc7-2e62a7cc9dcd.png)

My info window is showing all together with dismatch design (I used given bubble layout, symbol_layer_info_window_layout_callout.xml) instead of one by one.  
Not mentioned to combine it with clustering demo.
Do you have any suggestion on this issue?
Any advices would be appreciated.  Thank you!
