### ISSUE TITLE
marker fade in/out animation 

### ISSUE THREAD

**Issue by basitsaleemmb** [mapbox/mapbox-android-demo#883]
@tobrun 

how can i add animation of fade out to maker
here you go :

mapboxMap.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
@override
public boolean onMarkerClick(@nonnull Marker marker) {
// add fade out animation to marker here

                  }
}

**Comment by langsmith** [comment]
Hey @basitsaleemmb , thanks for using Mapbox!  I would recommend that you use a SymbolLayer for your icons, rather than markers.

Here's how to add SymboLayer markers: https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java

If you change animator object values and change `iconSize` to `iconOpacity` in the following lines, you should get what you're looking for:
https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java#L137

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java#L154


<img width="776" alt="screen shot 2018-10-11 at 7 33 23 am" src="https://user-images.githubusercontent.com/4394910/46811639-04570d80-cd28-11e8-8dc6-7a3ff99cdb74.png">


![ezgif com-resize](https://user-images.githubusercontent.com/4394910/46811628-fe612c80-cd27-11e8-8ccc-71223ae730ce.gif)

**Comment by basitsaleemmb** [comment]
thnku @langsmith , @tobrun

**Comment by basitsaleemmb** [comment]
@langsmith 
Why u guys don't want to add fading animation to simple marker rather than adding symbol layer.
