### ISSUE TITLE
I can't get my location 

### ISSUE THREAD

**Issue by wuxuenan** [mapbox/mapbox-android-demo#904]
![_20181106164748](https://user-images.githubusercontent.com/13412044/48052773-db6d4f80-e1e3-11e8-9486-c69317abb24e.jpg)
  sdk version 6.6.5

**Comment by langsmith** [comment]
Hi @wuxuenan , thanks for using Mapbox!  

I'm not sure what you've tried, what your code setup currently looks like, what you're seeing in the log cat, where you're located, etc. 

Please take a look at these two resources that could provide guidance:

- https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationComponentActivity.java

- https://www.mapbox.com/android-docs/maps/overview/location-component/

Because this repo's issue queue is used for problems with the app, [please contact Mapbox support](https://www.mapbox.com/contact/support/) if you still need help.
