### ISSUE TITLE
Rotate and change position for markers in latest MapBox SDK 6.7

### ISSUE THREAD

**Issue by Abhishek284** [mapbox/mapbox-android-demo#928]
Mapbox Android SDK: 6.7.0

The requirement in the application we are developing is that we have to change the LatLng of the marker and rotate with some bearing continuously. In the old mapbox version(4.2.1), we could do it without any issues.

```
////Working code with MapBox SDK 4.2.1////
MarkerViewOptions markerViewOptions = new MarkerViewOptions();
        IconFactory iconFactory = IconFactory.getInstance(this);
        Icon arrowIcon = iconFactory.fromResource(R.drawable.compass_needle);
        markerViewOptions.icon(arrowIcon);
        markerViewOptions.position(new LatLng(position)).rotation((float) headDirection);
        marker = mapboxMap.addMarker(markerViewOptions);

    ////For updating////

        marker.setPosition(new LatLng(aircraftLocation));
        marker.setRotation((float) headDirection);
        mapboxMap.updateMarker(marker);

```

In the latest Mapbox update, MarkerView and MarkerViewOptions is deprecated. We are trying to achieve the same functionality with Marker and MarkerOptions. But we are unable to rotate the marker.

We also tried using the SymbolLayer. The same functionality has been made complicated to implement in Symbol layer. 

Is there a way to achieve rotation and changing LatLng position of a marker in latest SDK?

**Comment by langsmith** [comment]
Hi @Abhishek284 , thanks for using Mapbox. Go ahead and use `6.7.2`, which is the latest version of the Mapbox Maps SDK for Android. Issues in this repo are for problems with this demo app specifically. I'm going to close this ticket because this is a general help question. Please continue the conversation at https://www.mapbox.com/contact/support/#products/android

You should use a `SymbolLayer`. You can work off of the code that I've written below. There is also the [Annotation plugin](https://www.mapbox.com/android-docs/plugins/overview/annotation) if you'd like to deal with less boilerplate code. There is also [the Markerview plugin](https://www.mapbox.com/android-docs/plugins/overview/markerview/), but I'd highly recommend you stick with the `SymbolLayer`. The `SymbolLayer` is much more performant and provides many more styling options.


**Setting up the `SymbolLayer`:**

```java
 Bitmap compassNeedleSymbolLayerIcon = BitmapFactory.decodeResource(
      BasicSymbolLayerActivity.this.getResources(), R.drawable.compass_needle);

mapboxMap.addImage("compass-needle-image-id", compassNeedleSymbolLayerIcon);


GeoJsonSource geoJsonSource = new GeoJsonSource("geojson-source", Feature.fromGeometry(Point.fromLngLat(LONGITUDE,LATITUDE)));
    mapboxMap.addSource(geoJsonSource);



SymbolLayer aircraftLayer = new SymbolLayer("aircraft-layer", "geojson-source")
      .withProperties(
          PropertyFactory.iconImage("compass-needle-image-id"),
          PropertyFactory.iconRotate(headDirection),
          PropertyFactory.iconIgnorePlacement(true),
          PropertyFactory.iconAllowOverlap(true)
          );
mapboxMap.addLayer(aircraftLayer);
```


**When bearing/location changes:**

```java
GeoJsonSource source = mapboxMap.getSourceAs("geojson-source");
if (source != null) {

source.setGeoJson(Feature.fromGeometry(Point.fromLngLat(newLongitude,newLatitude)));

aircraftLayer.setProperties(
  PropertyFactory.iconRotate(newHeadDirection)
);

}
```
