### ISSUE TITLE
Set custom color on marker

### ISSUE THREAD

**Issue by SmartSquard** [mapbox/mapbox-android-demo#945]
Hello 

I stuck into one situation , how can i set  custom color to marker of mapbox.. Like if I have imageview then we can set tint color , I am finding similar to tint color.
I guess is there any method using that I can achieve this functionality.

Thank you so much.

**Comment by langsmith** [comment]
Hi @SmartSquard , thanks for using Mapbox! 

`SymbolLayer`s and `SymbolLayer` icons give you fine control over the image/color of your marker. [The Annotation Plugin](https://www.mapbox.com/android-docs/plugins/overview/annotation/) makes it easier to interact with `SymbolLayer`s. You can also look into [the MarkerView plugin](https://www.mapbox.com/android-docs/plugins/overview/markerview/) to adjust a custom Android `View` and the `View`'s color.

I'm going to close this issue because this is a question about using Mapbox, rather than a problem with the demo app. Please contact Mapbox support via https://https://www.mapbox.com/contact/support/#products to continue the conversation about your Mapbox usage. Thank you!

**Comment by SmartSquard** [comment]
please show me one example.
