### ISSUE TITLE
map box on web development 

### ISSUE THREAD

**Issue by poojaPatel6994** [mapbox/mapbox-android-demo#946]
this is my full map box code where markers work but i have problem with change color marker.
when i have try to change marker color but not work please help me .
this is PHP file but not support in upload so uploaded txt file. 
[map.txt](https://github.com/mapbox/mapbox-android-demo/files/2707688/map.txt)

**Comment by langsmith** [comment]
Hi @poojaPatel6994  , thanks for using Mapbox!

I'm going to close this issue because this is a question about using Mapbox, rather than a problem with the Android demo app. Please contact Mapbox support via https://www.mapbox.com/contact/support/#products/web to continue the conversation about your Mapbox usage. Thank you!
