### ISSUE TITLE
Restrict Camera example uses deprecated Polygon methods/classes

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-android-demo#949]
https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/camera/RestrictCameraActivity.java

Tried to copy this, but somehow it doesn't work for me. Gonna look further, but intellij says the methods are deprecated.

**Comment by carstenhag** [comment]
Tried out the RestrictCameraActivity in my own (almost empty) app with com.mapbox.mapboxsdk:mapbox-android-sdk:7.0.0, the screen just stays blank. Something is bugged it seems.

**Comment by langsmith** [comment]
Hey @carstenhag , thanks for using Mapbox. [This pr](https://github.com/mapbox/mapbox-android-demo/pull/917) is updating the demo app's examples so that they work with `7.0.0` of the Maps SDK.  

Changes related to the `RestrictionCameraActivity`:

- https://github.com/mapbox/mapbox-android-demo/pull/917/files#diff-02c8f8f76e3b43d7050c8d889ae73d32

- https://github.com/mapbox/mapbox-android-demo/pull/917/files#diff-740e10b830b86ffb18d2fb7a6ae9f4c4

The example works for me on that pr/branch. If it doesn't for you, please let me know.

Also, [here's our migration guide to `7.x.x`](https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide)
