### ISSUE TITLE
Using different user defined icons for Symbol Layer

### ISSUE THREAD

**Issue by OchiengHosea** [mapbox/mapbox-android-demo#968]
There is the data driven styling for android mapbox, however, it uses "poi-15" as its icon library and system defined logic to determine which icon for a particular data.

However, i want more control over this, say if i have cereals data, and i want to show different icon for a particular cereal category, like a custom desined icon for maize, another different one for beans, another different one for peas. These have their properties defined in a GeoJson source.

How do i go about it?

**Comment by langsmith** [comment]
Hey @OchiengHosea , thanks for using Mapbox. 

This is a Mapbox implementation question rather than an issue with the actual demo app, so I'm going to go ahead and close this issue. 

Please continue the conversation via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 and our team will get you squared away.
