### ISSUE TITLE
Add external data 

### ISSUE THREAD

**Issue by JiLiren** [mapbox/mapbox-android-demo#976]
I tried to add our company's vector data in the Map APP, but found that the data request link sent by the Mapbox has an HTTP/1.1 suffix at the end, which causes our data department to be unrecognizable. Is there any way to get rid of it?

**Comment by JiLiren** [comment]
![default](https://user-images.githubusercontent.com/19288651/53230315-630e9980-36c1-11e9-82ad-de8a21de93e3.png)
You can refer to this picture, this is the request link for the added data provided in the Demo. There is a http/1.1 behind

**Comment by JiLiren** [comment]
![default](https://user-images.githubusercontent.com/19288651/53230504-c8628a80-36c1-11e9-9a4c-bd9ac3371b40.png)
This is the request link I made using mapbox, and there is an HTTP at the end, which causes our GeoServer server to recognize this link as the wrong link.

**Comment by langsmith** [comment]
Hi @JiLiren , thanks for using Mapbox!

I'm going to close this issue because this is a question about using Mapbox, rather than a problem with the Android demo app. Please contact the Mapbox support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 and they'll get you squared away. Thank you!
