### ISSUE TITLE
Cluster many sources together

### ISSUE THREAD

**Issue by donkii** [mapbox/mapbox-android-demo#981]
Is there any way to cluster many sources together into one big cluster? I don't seem to find a solution for that.

**Comment by langsmith** [comment]
Hi @donkii  , thanks for using Mapbox!

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleLayerClusteringActivity.java and https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ImageClusteringActivity.java show how to use layers and sources in conjunction with one another.

I'm going to close this issue because this is a question about using Mapbox, rather than a problem with the Android demo app. Please contact the Mapbox support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 and they'll get you squared away. Thank you!
